export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAIL = "GET_TASKS_FAIL";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAIL = "GET_TASK_FAIL";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAIL="GET_USER_FAIL";
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL="UPDATE_USER_FAIL";
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL="DELETE_USER_FAIL";

export const GET_IMAGE_SUCCESS="GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAIL="GET_IMAGE_FAIL";
export const ADD_IMAGE_SUCCESS="ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAIL="ADD_IMAGE_FAIL";
export const DELETE_IMAGE_SUCCESS="DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAIL="DELETE_IMAGE_FAIL";

// update?
